### ISSUE TITLE
addComponentAsRefTo Invariant Violation

### ISSUE THREAD

**Issue by Riccardo-Zanutta** [JodusNodus/react-qr-reader#1]
Hi,
I have some problem integrating this component in my pure React application.
this is the code:

[QrCode](https://gist.github.com/Riccardo-Zanutta/74ab3013dc4d58de739a53fbb6afa2b5)

[Login](https://gist.github.com/Riccardo-Zanutta/4f45589483921ff8d7cc926da2131c36)

And this is the error message I found:

addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Already tried this: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105 . Removed npm_modules/ folder and `npm install` again but didn't work. Any clue about that? 
Thanks

**Comment by gregogalante** [comment]
I have the same problem too..

**Comment by JodusNodus** [comment]
I am looking in to this. I first though the problem was that i required react as a dependency and not as a peer dependency. But the problem still occurs.

**Comment by Riccardo-Zanutta** [comment]
@JodusNodus thanks, if you need any help, I'm available.

**Comment by JodusNodus** [comment]
It should work now. In the test i was able to use a ref without any errors. I will publish this to npm as version 0.2.4. If it works for you then we can close the issue.

**Comment by Riccardo-Zanutta** [comment]
Thanks @JodusNodus, now it's working fine. We can close the issue :)
