### ISSUE TITLE
facingMode

### ISSUE THREAD

**Issue by adamk5550** [JodusNodus/react-qr-reader#10]
using facingMode you get the error overconstrainedError

<QrReader
          handleError={this.handleError}
          handleScan={this.handleScan}
          facingMode={'rear'}
          interval={2000} />}

**Comment by JodusNodus** [comment]
This is because some browsers don't support predefining the camera. Chrome desktop is the one i know.

**Comment by adamk5550** [comment]
hrm yeah, got it working in firefox for android. All versions of chrome seem to throw that error.

**Comment by akash0675** [comment]
wouldn't work in chrome if your site doesn't follow HTTPS. It'll run **locally** on your desktop, but you cannot wild test it on your phone or any other desktop.

**Comment by akash0675** [comment]
P.S. facingMode works fine in my application.

**Comment by adamk5550** [comment]
The site was running on HTTPS however still got the overconstrained error. I just used firefox for my demo and it worked perfectly. Cheers folk!

**Comment by JodusNodus** [comment]
The problem is that chrome does not support the facingMode constraint although it is in the w3c spec for getUserMedia. [Bug Report](https://bugs.chromium.org/p/chromium/issues/detail?id=290161)

**Comment by JodusNodus** [comment]
This means that you cannot choose which facingMode to choose on chrome. If you just don't specify the facingMode it will work fine.

**Comment by jerefrer** [comment]
I just ran into this issue as well.

The _funny_ thing is that it used to work properly. I just tested with `Chrome 51.0.2704.81` on my Android (Fairphone) and `Chrome 49.0.2623.110 (64-bit)` on ArchLinux and it's working perfectly.

When testing with chrome 54.x on Windows or a newer Android it breaks with `OverconstrainedError`.

Not very nice of you Google ... 

For now we told the client to switch to Android Firefox.

Is there a way to still force the use of the rear camera without getting this error ?

**Comment by jerefrer** [comment]
We tried switching to Firefox, but for me I still have the same issue as before (https://github.com/JodusNodus/react-qr-reader/issues/6), even after updating the app.

For my co-worker it's working but it seems it's very hard to get the QrCode to be recognized.

Also he gets asked permission to access the camera every time the component is loaded, so before each scan he has to say Yes.

**Comment by JodusNodus** [comment]
That is a bummer to hear. I am really busy right now so i don't have the time to look into the issue, if no one opens a PR then i will try to make some free time at the end of the week.

**Comment by jerefrer** [comment]
@JodusNodus There's no rush from our side, please don't stress over this :wink:

**Comment by iqbalmineraltown** [comment]
I was downloading this package via `npm` last week. I believe it says version `0.3.1`. 

On android Chrome it wont use rear camera although I've already set `facingMode={`rear`}`. But on android Firefox it ask which camera and I can use both front and rear camera

Last friday, one of my colleague tried to download this component directly from github, and include this in our project. It works! Now our app can access rear camera from Android Chrome and scan QR code.

Is there any chance you haven't update the `npm` package?
I know this wasn't much an issue, but I thought I should let you know that something happened

**Comment by JodusNodus** [comment]
@iqbalmineraltown The version is correct, but it still used the `facingMode` constraint as provided by the w3c `getUserMedia` spec. The `facingMode` spec has not been equally implemented across browsers. Because of this i decided to find another way around. In the new device picker it requests all available devices and then tries to figure out which one is front or rear facing. By then specifying the exact device id it forces “most” browsers of picking that one without any prompting of the user.

I haven’t had much time to test it and improve it, so that is why it has not been released. I am glad that it works for you and if you find any bugs, be sure to open an issue.

[New device picker commit](https://github.com/JodusNodus/react-qr-reader/commit/0657b21f58b8a5e5e8ef837004707e976205dd8c)
