### ISSUE TITLE
Not working in android chrome

### ISSUE THREAD

**Issue by pcegarra** [JodusNodus/react-qr-reader#100]
Im using it on a Xioami MI A1, and with firefox its working ok, but using brave or google chrome, the screens turns black, seems like only captures one frame, one time.
Any idea?

**Comment by apuntovanini** [comment]
Confirmed on Safari and Chrome IOS, error for us is: TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getSupportedConstraints')

**Comment by WilliamKatz** [comment]
Hey yall, have you found a workaround?  I also experience this on iOS 12.1.1.  Ill try iOS 12.1.2 and update this

**Comment by JodusNodus** [comment]
Should be fixed in new version `2.1.2`
