### ISSUE TITLE
What was released in 2.1.2?

### ISSUE THREAD

**Issue by lnhrdt** [JodusNodus/react-qr-reader#103]
I saw today that there's a new version (v2.1.2) in npm! Thanks @JodusNodus!

However I can't seem to find any release notes. The releases page in GitHub only mentions 2.1.1.

I also checked the README, [npmjs.org](https://www.npmjs.com/package/react-qr-reader), the branches, the tags, etc for some clue as to what was in the release but I couldn't find anything. Before I upgrade I'd like to know what was in the release. Can you create some release notes in GitHub or elsewhere that communicate what was in the release?

**Comment by JodusNodus** [comment]
Its such a small release so I forgot to make a release, just a merge of a bug that stopped some Chrome versions from being compatible.

https://github.com/JodusNodus/react-qr-reader/releases/tag/v2.1.2
