### ISSUE TITLE
Autofocus issues on some older phones

### ISSUE THREAD

**Issue by randohinn** [JodusNodus/react-qr-reader#105]
I'm seeing problems, where the camera does not autofocus in Chrome, on some older phones, such as the LG G4. Supposedly, focus on there does not work at all - it will not focus on anything, qr code or not. 

Should I manually tie into the focusmode somehow, or what's the best case to tackle this?

**Comment by JodusNodus** [comment]
This is not controllable through the `getUserMedia` API as such this is out of the scope of this module.
