### ISSUE TITLE
Can't recognize particular QR

### ISSUE THREAD

**Issue by ivankonanykhin** [JodusNodus/react-qr-reader#107]
Can't seem to recognize this particular QR code:
![image](https://user-images.githubusercontent.com/13839593/53345549-9c980c80-392e-11e9-9bf2-6d42c2fae26a.png)

**Comment by JodusNodus** [comment]
The QR code seems to scan perfectly fine.

**Comment by julia-kits** [comment]
No, it doesn't
Even your demo doesn't recognise this qr code
![image](https://user-images.githubusercontent.com/20840929/53488535-a55c2000-3a9f-11e9-8089-ab2e04afe655.png)

**Comment by JodusNodus** [comment]
The demo isn't on the latest version. Tested it out with the latest version and it works fine.
