### ISSUE TITLE
Can't read QR on chrome android after refresh

### ISSUE THREAD

**Issue by OPaquay** [JodusNodus/react-qr-reader#111]
Hi,

We are using react-qr-reader in a project at work and we are having an issue while testing it on Chrome Android.

It works perfectly on the desktop browser but with chrome on the android smartphone it works only when you first launch the page. 

If I refresh the page or I lock the phone, when I come back to the page and try to read a QR it never triggers the onError or onScan functions.

Version: 2.2.0
Android: 8.0.0

Thanks in advance

**Comment by JodusNodus** [comment]
Im currently not able to test on an Android device. So it still show's the camera stream, but the scanning is not resumed?

**Comment by OPaquay** [comment]
Yes exactly ! 
I've been trying to find the problem for the whole morning and it resolved itself after I ate my soup, so maybe soup is the answer.
I'll let you know if I have this problem again in the future. Still weird.

**Comment by JodusNodus** [comment]
Soup is definitely a force of good in this world so.

**Comment by chitainguyen** [comment]
> Yes exactly !
> I've been trying to find the problem for the whole morning and it resolved itself after I ate my soup, so maybe soup is the answer.
> I'll let you know if I have this problem again in the future. Still weird.

Please share how can you resolved it. It still errors when i build on cordova
