### ISSUE TITLE
Camera would keep on when rapidly turn reader on & off

### ISSUE THREAD

**Issue by wildskyf** [JodusNodus/react-qr-reader#112]
reproduce steps:

1. open storybook
2. switch to 'on and off'
3. rapidly click the 'turn on' button three times.

and you will see the reader is stop, but the device camera is still on

**Comment by wildskyf** [comment]
This issue might caused by `/src/index.js:L173`
Component would get into infinite call when we remove the `<QRReader>` before the reader loaded.

**Comment by wildskyf** [comment]
ref:

* #71 
* #142906e

**Comment by wildskyf** [comment]
hello?

**Comment by Nasaakaa** [comment]
@wildskyf my camera is not loading at all. How can i enable my phone camera?
