### ISSUE TITLE
Disable scan dynamically either via interval or boolean?

### ISSUE THREAD

**Issue by DannyLingard** [JodusNodus/react-qr-reader#13]
I've tried passing interval={this.state.interval} to the component, it works in the initial constructor but not when state changes through handleScan(). I'm changing the interval to 10000 via setState but it's not re-rendering/updating <QrReader> based on the new interval.

I'm essentially trying to throttle (via 10000 ms) or preferably disable the scan after a successful scan. I'm deploying an overlay component via this.state.scanSuccess, which works fine, just hoping to disable/throttle the scanner without unmounting the component. A method to disable would be awesome :)

Thanks,
Danny

**Comment by JodusNodus** [comment]
Thanks for making this issue. A method to disable it doesn't look like the best or the most reactish solution to me. A better solution might be to disable it all together by passing the interval option `false` and have the component adapt to changes in the interval prop?

**Comment by DannyLingard** [comment]
Awesome, interval option false would fit perfectly. Cheers and keep up the good work :)

**Comment by JodusNodus** [comment]
v0.3.1 will be out tonight containing this implementation.
