### ISSUE TITLE
Safari: Don't ask to allow access camera.

### ISSUE THREAD

**Issue by vctqs1** [JodusNodus/react-qr-reader#136]
On Phone: Don't ask to allow access camera.

ask on safari in Macbook Pro.
But it don't working. It can't use camera of laptop.

![Screen Shot 2019-09-13 at 3 39 39 PM](https://user-images.githubusercontent.com/30227910/64849039-b7b53a00-d63c-11e9-94f1-b5845e1b3825.png)
`
                <div>
                    <QrReader
                        delay={300}
                        onError={this.handleError}
                        onScan={this.handleScan}
                        style={{
                            height: 240,
                            width: 320,
                        }}
                    />
                    <p>{result}</p>
                </div>`
 
![Screen Shot 2019-09-13 at 3 41 43 PM](https://user-images.githubusercontent.com/30227910/64849215-1975a400-d63d-11e9-933e-b6f3ab9fa995.png)

I write code to show logs.
![Screen Shot 2019-09-13 at 3 41 54 PM](https://user-images.githubusercontent.com/30227910/64849214-1975a400-d63d-11e9-912f-9d1fd6840a6f.png)

Its result when access on phone
![Image from iOS](https://user-images.githubusercontent.com/30227910/64849238-285c5680-d63d-11e9-94f2-3709cbd93f57.png)

**Comment by taneba** [comment]
@vctqs1 
I had the same issue, and it turned out that it doesn't work on iOS Safari unless connecting with https. So you can test by creating a secure tunnel (e.g. by using ngrok).

**Comment by govi92** [comment]
> @vctqs1
> I had the same issue, and it turned out that it doesn't work on iOS Safari unless connecting with https. So you can test by creating a secure tunnel (e.g. by using ngrok).

It worked for me. thanks :D

**Comment by vctqs1** [comment]
> @vctqs1
> I had the same issue, and it turned out that it doesn't work on iOS Safari unless connecting with https. So you can test by creating a secure tunnel (e.g. by using ngrok).

many thanks
