### ISSUE TITLE
Camera doesn't work on iOS PWA home app mode

### ISSUE THREAD

**Issue by faradaytrs** [JodusNodus/react-qr-reader#140]
Is it possible to use HTML Media Capture instead of getUserMedia? 
It seems to be working even in PWA mode, although it is not real time.
https://stackoverflow.com/questions/46228218/how-to-access-camera-on-ios11-home-screen-web-app

WebRTC video doesn't work in PWA app on safari.

**Comment by Ferigit** [comment]
Does anybody have any solution for this? is it ok to open the browser in between and scan the qrcode then return to pwa mode? is it right or not professional!?
