### ISSUE TITLE
Problem with iPhone iOS v 12

### ISSUE THREAD

**Issue by buglessir** [JodusNodus/react-qr-reader#145]
I've checked the demo with iPhone iOS v12.4.1 but doesn't support camera ?!

**Comment by huxiulin** [comment]
me too

**Comment by AddoSolutions** [comment]
Same, any ideas?

**Comment by AddoSolutions** [comment]
Interesting, it works on his site but NOT on my  dev server… curious

**Comment by ehayon** [comment]
@AddoSolutions Make sure you are serving over https - iOS won't allow you to use the camera unless you are using HTTPS.

**Comment by AddoSolutions** [comment]
Indeed, so I just found out.  Fortunately it works on an invalid cert though :)

Thanks!
