### ISSUE TITLE
Supports of the getUserMedia

### ISSUE THREAD

**Issue by peteroid** [JodusNodus/react-qr-reader#15]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), we can do something like:
```
var getUserMedia = (navigator.getUserMedia ||
      navigator.webkitGetUserMedia ||
      navigator.mozGetUserMedia);
```
to support some older browsers. 

Would it be possible to add these?

**Comment by JodusNodus** [comment]
This is not needed as the [polyfill](https://github.com/mozdevs/mediaDevices-getUserMedia-polyfill) that is included should cover those older API’s. If you have any specific case where it isn’t, please let me know.
