### ISSUE TITLE
The camera does not work

### ISSUE THREAD

**Issue by mahmoudabid8** [JodusNodus/react-qr-reader#174]
This is what appears when I open the component
                      
![Capture](https://user-images.githubusercontent.com/71451151/93487038-c9d75180-f8fc-11ea-989f-f81abc717277.PNG)

I use the functional components
 
 `<QrReader
                          delay={300}
                          onError={handleError}
                          onScan={handleScan}
                          style={{ width: '100%' }}
                        />`

**Comment by cakesoft-nikhita** [comment]
@mahmoudabid8 
how you solved this issue? It's on any specific platform?
