### ISSUE TITLE
Upgrade peer dependency to react 17?

### ISSUE THREAD

**Issue by Quesstor** [JodusNodus/react-qr-reader#183]
I just upgraded to react@17.0.1 and now get a dependency error (see below).

Is it possible to upgrade the peer dependency to v17?

Full error log:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nextjs@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"~16" from react-qr-reader@2.2.1
npm ERR! node_modules/react-qr-reader
npm ERR!   react-qr-reader@"^2.2.1" from the root project
```

**Comment by amacwhirter** [comment]
@Quesstor a workaround with npm v7 is to add the `--legacy-peer-deps` flag to install - this will ignore all peerDependencies while installing similar to v4 - v6.

https://docs.npmjs.com/cli/v7/commands/npm-install

**Comment by Quesstor** [comment]
Thanks, i will close this issue although i still think it would be best to upgrade the peer dep to the new react version.
