### ISSUE TITLE
Not working on Mobile devices on localhost

### ISSUE THREAD

**Issue by dhlpradip** [JodusNodus/react-qr-reader#190]
It works perfectly on PC browsers but when I try to open it in mobile devices on production through localhost, it shows the viewfinder but can't open camera. 
Camera permission is allowed to browser and I haven't checked on hosted environment
![20210325_120854](https://user-images.githubusercontent.com/25703330/112428288-0b8cfd00-8d63-11eb-8f85-f3de43b8bc67.jpg)

**Comment by joshi008** [comment]
@dhlpradip How was the issue resolved?

**Comment by nastassiadanilova** [comment]
@joshi008 use https
