### ISSUE TITLE
Can someone provide me with a working code snipper regarding "facingMode" being set on iOS Safari browsers?

### ISSUE THREAD

**Issue by tempuslight** [JodusNodus/react-qr-reader#197]
I'm using this library to read QR codes in my ReactJs website. When using an Android device, I can change "facingMode" to "user" or "environment" and it seems to switch naturally. However, when I try the same code on iOS, it will always have the front/user camera, never the rear one? Even though I select it with facingMode?  

Here's my code: 

```
import QrReader from "react-qr-reader";

const Scanner2 = ({ handleError, handleScan }) => {
  const [selfie, setSelfie] = useState(false);

  return (
    <div className="g-column g-centralize">
      <Button onClick={() => setSelfie(!selfie)}>
        <FlipCameraIos color="primary" fontSize="large" />
      </Button>
      <Card className="c-scanner">
        <QrReader
          onError={handleError}
          onScan={handleScan}
          //facingMode={selfie ? "user" : "environment"}
          className="c-scanner__qr"
          constraints={
              {
                  video: {
                      facingMode: { exact: selfie ? "user" : "environment"}
                  }
              }
          }
        />
      </Card>
    </div>
  );
};

export default Scanner2;
```

So I have a  button that will change the setSelfie hook and it works on Android. As you can also see, I've tried setting "facingMode" with constraints instead of just the property on the QrReader component, but this has the same results: works on Android, just has front/user camera for iOS. 

I've tried the demo here (https://www.thomasbilliet.com/react-qr-reader/) on iOS and it works? I can change camera's! But I can't seem to find anywhere, how this is done in the demo. I'm guessing something else/extra than just setting facingMode="environment" or something.  

Can anyone who got this working currently on iOS provide me with a small code snippet, like above, so I can make my QrReader also work properly on iOS, with both camera's? Or tell me what settings to set, etc...?

Thanks in advance!

**Comment by AndreyPatseiko** [comment]
Have similar problem.
Try remove **constraints** props. After that on IOS you can switch camera. Try it.

**Comment by tempuslight** [comment]
> I have similar problem.
> Try remove **constraints** prop. After that on IOS you can switch camera. Try it.

Hi! That didn't work, HOWEVER, I removed the package, remove the <QrReader> component, reinstalled the package and then re-added the component. Magically, now it works! Including the changing of camera :D. Strange, this wasn't really an issue but weird nonetheless. Anyway thanks for replying and helping :') .
