### ISSUE TITLE
Lib not working on OS X/Chrome and Android/Chrome

### ISSUE THREAD

**Issue by marekwilniewiec** [JodusNodus/react-qr-reader#21]
Tried to use the lib on OS X. I can see the camera video on Chrome but Im not getting any callbacks (onScan or onError). I see that there is a Chrome helper process running, using around 50% of my CPU when delay is set to 100 but thats it. I also tested your demo and it doesn't work on both (MacOS or Android 6.0). Video is visible but there is no result of scanning. Didn't test other devices. Legacy mode worked fine after providing an image of a QR code - I get callbacks every 'delay' ms.

**Comment by marekwilniewiec** [comment]
I think that there is something wrong with the output in lib folder. I cloned repo, used 'gulp build', linked project and it works. I can see that I have many changes comparing to lib in repo.

**Comment by JodusNodus** [comment]
The demo works on my macbook pro with macOs Sierra, and on my moto g with android 6.0.1. On older devices it can take a bit longer, or it might never get recognised because of lightning, etc. But the QR-code algorithm is the best and fastest pure client-size javascript.

Could you provide more information about your devices and browsers?

**Comment by marekwilniewiec** [comment]
As I've said [on this site](https://jodusnodus.github.io/react-qr-reader/) I always see Decoded QR-Code: No result, no matter how I scan the QR code. Im getting the same result when using your lib in my project (npm install react-qr-reader). 
I downloaded your repo on the same machine (OSX El Capitan 10.11.3), run 'gulp build' (generated lib folder content has changed), linked your project to my own project and it works fine.
Please make sure that your generated lib folder is as you would expect.

**Comment by gtabmx** [comment]
Can confirm, I am getting the same issue as marekwilniewiec on both OS X El Capitan 10.11.3 Chrome and on Andoird Chrome.

**Comment by JodusNodus** [comment]
I am looking into it. Does it work when you run storybook?

**Comment by JodusNodus** [comment]
It might have something to do with a bug in a previous release. I have updated the demo to the newest version. Please test it out.

**Comment by gtabmx** [comment]
Great! Works now!
