### ISSUE TITLE
Example for LegacyMode Usage

### ISSUE THREAD

**Issue by mervintankw** [JodusNodus/react-qr-reader#23]
Hi Is there anywhere i can find an example on how to use the LegacyMode of this qr reader?

**Comment by mervintankw** [comment]
I have managed to get an example of the legacy mode running. Here's the code in case anyone is looking for one.

```javascript
import React, { Component } from "react";
import QrReader from "react-qr-reader";

class Test extends Component {

    constructor(props){
        super(props)
        this.state = {
            delay: 100,
            result: 'No result',
        }

        this.handleScan = this.handleScan.bind(this)
    }
    handleScan(data){
        this.setState({
            result: data,
        })
    }
    handleError(err){
        console.error(err)
    }
    openImageDialog() {
        this.refs.qrReader1.openImageDialog()
    }

    render(){
        const previewStyle = {
            height: 240,
            width: 320,
        }

        return(
            <div>
                <QrReader ref="qrReader1"
                    delay={this.state.delay}
                    previewStyle={previewStyle}
                    onError={this.handleError}
                    onScan={this.handleScan}
                    legacyMode={true}
                />
                <input type="button" value="Submit QR Code" onClick={this.openImageDialog.bind(this)} />
                <p>{this.state.result}</p>
            </div>
        )
    }
}
```

**Comment by JodusNodus** [comment]
Sorry for my late response. 👍 Thanks for the example I will put it in the repo.

**Comment by DannyLingard** [comment]
Is it possible to get the Legacy Mode implemented on the Demo on Github Pages? It doesn't work on my iPad Air (2?) with Safari, it throws an error message. I can't recall what the error says but let me know if you want it and I'll update the comment. Thanks

**Comment by mervintankw** [comment]
@DannyLingard could you try your iPad Air with my site? http://staging.e-attendee.com/demo. It is implemented with the sample code above.

**Comment by JodusNodus** [comment]
@DannyLingard Yes that was the plan but i forgot about it.

**Comment by DannyLingard** [comment]
@mervintankw just tested it and it works for both camera -> take photo, and select photo (from which I loaded a screen shot). Didn't test iCloud though as I don't use it but will try it in next few days. I'll also test Chrome on iOS to see how other browsers behave on the platform. I originally had an older version of iOS and the camera didn't work. I managed to free up enough space for the update so now it all works.

@JodusNodus is there a way you recommend setting legacy mode dynamically? Will the onError() fire for non supported devices, allowing us to set in local component state? I see the readme mentions "unsupported platforms" in onError() but just checking they're one and the same.

**Comment by JodusNodus** [comment]
@DannyLingard Great to hear that it works. And yes the legacyMode, interval can all be changed dynamically without the need for unmounting.

**Comment by JodusNodus** [comment]
Demo has been updated to use legacyMode as the fallback. The code is in the `gh-pages` branch.

**Comment by DannyLingard** [comment]
Thanks for the update, I just revoked camera permissions for the demo and the onError() handles the blocking of permissions as well. Legacy mode works well for current Chrome mobile.

**Comment by DannyLingard** [comment]
@JodusNodus is there a method to removeImage() or similar? I'd like to call it within the onScan() method so I can essentially reset it.

**Comment by JodusNodus** [comment]
@DannyLingard No there isn’t a method like that. But i don’t want to add another method if a more reactish solution can be found. Maybe an onImageLoad handler so you can just hide the element and show it again when a new image is loaded?

**Comment by alluster** [comment]
@JodusNodus Hey, great work this one! Liking this QR reader a lot 👍. I'm struggling with one minor thing. I'm using the legacyMode, when I choose an image from a file on my Mac and chrome, the QR is read well. Then when I do the same with my iPhone and Chrome (or safari), the image I take simply stays on the screen and the app doesn't read the QR...  what am I not getting right here

QR Reader:

![image](https://user-images.githubusercontent.com/21972091/37906616-68915738-310b-11e8-8a34-75f85048216b.png)

The button on the App.js:
![image](https://user-images.githubusercontent.com/21972091/37906649-7bdd7aa6-310b-11e8-9ee0-380b4b1c7101.png)

**Comment by ujwaldreamztech** [comment]
I am stuck in the same place, has any solution been found?

**Comment by heysadboy** [comment]
@mervintankw @alluster I am unable to use refs for React 16.8. I saw we can use const qrReader = useRef(null); but I am unable to use it.

```
 const qrReader = useRef(null);

  const openImageDialog = () => {
    qrReader.openImageDialog()
  }

<QrReader
                      ref={qrReader}
                      delay={100}
                      onScan={handleScan}
                      onError={handleError}
                      resolution={800}
                      style={previewStyle}
                      legacyMode
                    />
                    <input type="button" value="Submit QR Code" onClick={openImageDialog} />
```

This is in a function.

**Comment by pupimarti** [comment]
> @mervintankw @alluster I am unable to use refs for React 16.8. I saw we can use const qrReader = useRef(null); but I am unable to use it.
> 
> ```
>  const qrReader = useRef(null);
> 
>   const openImageDialog = () => {
>     qrReader.openImageDialog()
>   }
> 
> <QrReader
>                       ref={qrReader}
>                       delay={100}
>                       onScan={handleScan}
>                       onError={handleError}
>                       resolution={800}
>                       style={previewStyle}
>                       legacyMode
>                     />
>                     <input type="button" value="Submit QR Code" onClick={openImageDialog} />
> ```
> 
> This is in a function.

Hi! You should change qrReader.openImageDialog() for qrReader.current.openImageDialog() 👍

**Comment by mdfaizan7** [comment]
For anyone here who wants to implement legacy mode using hooks:


```js
import React, { useState, useRef } from 'react'
import QrReader from 'react-qr-reader'
onst QrScanner = () => {
  const reader = useRef(null)
  const [code, setCode] = useState('')
  const handleScan = (data) => {
    setCode(data)
  }
  const handleError = (err) => {
    console.error(err)
  }
  const openImageDialog = () => {
    reader.current.openImageDialog()
  }
  return (
    <div>
      <QrReader
        ref={reader}
        onError={handleError}
        onScan={handleScan}
        legacyMode
      />
      <input type='button' value='Submit QR Code' onClick={openImageDialog} />
      <p>{code}</p>
    </div>
  )
}
export default QrScanner
```

**Comment by Hossam-Soliman** [comment]
> For anyone here who wants to implement the legacy mode using hooks:
> 
> ```js
> import React, { useState, useRef } from 'react'
> import QrReader from 'react-qr-reader'
> 
> onst QrScanner = () => {
>   const reader = useRef(null)
>   const [code, setCode] = useState('')
> 
>   const handleScan = (data) => {
>     setCode(data)
>   }
> 
>   const handleError = (err) => {
>     console.error(err)
>   }
> 
>   const openImageDialog = () => {
>     reader.current.openImageDialog()
>   }
> 
>   return (
>     <div>
>       <QrReader
>         ref={reader}
>         onError={handleError}
>         onScan={handleScan}
>         legacyMode
>       />
>       <button onClick={openImageDialog}>Sumbit a QR Code</button>
>       <p>{code}</p>
>     </div>
>   )
> }
> 
> export default QrScanner
> ```

Uncaught (in promise) TypeError: Cannot read property 'openImageDialog' of null

**Comment by dhlpradip** [comment]
Why the normal mode doesn't work when implemented legacy Mode? How can I use both the modes simultaneously?

**Comment by rey-caburnay** [comment]
legacyMode not working on the workstation/PC without camera?  I got this error and I think the reason why the refs is null because of this error?
DOMException: Requested device not found
console.<computed> @ index.js:1451
handleError @ qr-code.js:60
(anonymous) @ react-qr-scanner.esm.js:1474
Promise.catch (async)
(anonymous) @ react-qr-scanner.esm.js:1473
commitHookEffectListMount @ react-dom.development.js:19607
commitPassiveHookEffects @ react-dom.development.js:19644
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
flushPassiveEffectsImpl @ react-dom.development.js:22708
unstable_runWithPriority @ scheduler.development.js:656
runWithPriority$1 @ react-dom.development.js:11076
flushPassiveEffects @ react-dom.development.js:22676
performSyncWorkOnRoot @ react-dom.development.js:21591
(anonymous) @ react-dom.development.js:11130
unstable_runWithPriority @ scheduler.development.js:656
runWithPriority$1 @ react-dom.development.js:11076
flushSyncCallbackQueueImpl @ react-dom.development.js:11125
flushSyncCallbackQueue @ react-dom.development.js:11113
discreteUpdates$1 @ react-dom.development.js:21749
discreteUpdates @ react-dom.development.js:811
dispatchDiscreteEvent @ react-dom.development.js:4210

**Comment by csdevelopment01** [comment]
reader.current.openImageDialog() is not a function. help me out

**Comment by aedwards87** [comment]
having the same issue as above, reader.current.openImageDialog() is not a function.

**Comment by Fosy4u** [comment]
having same issue as the above

**Comment by ParasPuku** [comment]
import React, { useRef } from "react";
import { useState } from "react";
import QRCode from "qrcode";
import { QrReader } from "react-qr-reader";
import "./App.css";

function App() {
  const qrRef = useRef(null);

  const [text, setText] = useState("");
  const [imageURL, setImageURL] = useState("");
  const [scanResultFile, setScanResultFile] = useState("");
  const [scanResultWebCam, setScanResultWebCam] = useState("");

  const generateQRCode = async () => {
    try {
      const response = await QRCode.toDataURL(text);
      setImageURL(response);
    } catch (error) {
      console.log(error);
    }
  };

  const onScanFile = () => {
    console.log(qrRef); // {current: null} - on first render current value coming as null 
    if (qrRef.current !== null) {
      qrRef.current.openImageDialog();
    }
  };

  const handleErrorFile = (error) => {
    console.log(error);
  };

  const handleScanFile = (result) => {
    if (result) {
      setScanResultFile(result);
    }
  };

  const handleErrorWebCam = (error) => {
    console.log(error);
  };

  const handleScanWebCam = (result) => {
    if (result) {
      setScanResultWebCam(result);
    }
  };

 <QrReader
      ref={qrRef}
      delay={300}
      style={{ width: "100%" }}
      onError={handleErrorFile}
      onScan={handleScanFile}
      legacyMode
    />

-->> I am also facing same issue  - 
Uncaught TypeError: Cannot read properties of null (reading 'openImageDialog')

**Comment by AbdulRazzaque** [comment]
`import React, {useState, useRef} from 'react';
import {Container, Card, CardContent, makeStyles, Grid, TextField, Button} from '@material-ui/core';
import QRCode from 'qrcode';
import {QrReader} from 'react-qr-reader';

const YoutubeQrcode = () => {
    const [text, setText] = useState('');
    const [imageUrl, setImageUrl] = useState('');
    const [scanResultFile, setScanResultFile] = useState('');
    const [scanResultWebCam, setScanResultWebCam] =  useState('');
    const classes = useStyles();
    const qrRef = useRef(null);
  
  
  
    const generateQrCode = async () => {
      try {
            const response = await QRCode.toDataURL(text);
            setImageUrl(response);
      }catch (error) {
        console.log(error);
      }
    }
    const handleErrorFile = (error) => {
      console.log(error);
    }
    const handleScanFile = (result) => {
        if (result) {
            setScanResultFile(result);
        }
    }
    const onScanFile = () => {
      qrRef.current.openImageDialog();
    }
    const handleErrorWebCam = (error) => {
      console.log(error);
    }
    const handleScanWebCam = (result) => {
      if (result){
          setScanResultWebCam(result);
      }
     }
  return (
    <Container className={classes.conatiner}>
          <Card>
              <h2 className={classes.title}>Generate Download & Scan QR Code with React js</h2>
              <CardContent>
                  <Grid container spacing={2}>
                      <Grid item xl={4} lg={4} md={6} sm={12} xs={12}>
                          <TextField label="Enter Text Here" onChange={(e) => setText(e.target.value)}/>
                          <Button className={classes.btn} variant="contained" 
                            color="primary" onClick={() => generateQrCode()}>Generate</Button>
                            <br/>
                            <br/>
                            <br/>
                            {imageUrl ? (
                              <a href={imageUrl} download>
                                  <img src={imageUrl} alt="img"/>
                              </a>) : null}
                      </Grid>
                      <Grid item xl={4} lg={4} md={6} sm={12} xs={12}>
                        <Button className={classes.btn} variant="contained" color="secondary" onClick={onScanFile}>Scan Qr Code</Button>
                        <QrReader
                          ref={qrRef}
                          delay={300}
                          style={{width: '100%'}}
                          onError={handleErrorFile}
                          onScan={handleScanFile}
                        //   legacyMode
                        />
                        <h3>Scanned Code: {scanResultFile}</h3>
                      </Grid>
                      <Grid item xl={4} lg={4} md={6} sm={12} xs={12}>
                         <h3>Qr Code Scan by Web Cam</h3>
                         <QrReader
                         delay={300}
                         style={{width: '100%'}}
                         onError={handleErrorWebCam}
                         onScan={handleScanWebCam}
                         />
                         <h3>Scanned By WebCam Code: {scanResultWebCam}</h3>
                      </Grid>
                  </Grid>
              </CardContent>
          </Card>
    </Container>
  )
}
const useStyles = makeStyles((theme) => ({
    conatiner: {
      marginTop: 10
    },
    title: {
      display: 'flex',
      justifyContent: 'center',
      alignItems:  'center',
      background: '#3f51b5',
      color: '#fff',
      padding: 20
    },
    btn : {
      marginTop: 10,
      marginBottom: 20
    }
}));

export default YoutubeQrcode`

i am facing this error Uncaught TypeError: Cannot read properties of null (reading 'openImageDialog') please help me

**Comment by AbdulRazzaque** [comment]
`import React, {useState, useRef} from 'react';
import {Container, Card, CardContent, makeStyles, Grid, TextField, Button} from '@material-ui/core';
import QRCode from 'qrcode';
import {QrReader} from 'react-qr-reader';

const YoutubeQrcode = () => {
    const [text, setText] = useState('');
    const [imageUrl, setImageUrl] = useState('');
    const [scanResultFile, setScanResultFile] = useState('');
    const [scanResultWebCam, setScanResultWebCam] =  useState('');
    const classes = useStyles();
    const qrRef = useRef(null);
  
  
  
    const generateQrCode = async () => {
      try {
            const response = await QRCode.toDataURL(text);
            setImageUrl(response);
      }catch (error) {
        console.log(error);
      }
    }
    const handleErrorFile = (error) => {
      console.log(error);
    }
    const handleScanFile = (result) => {
        if (result) {
            setScanResultFile(result);
        }
    }
    const onScanFile = () => {
      qrRef.current.openImageDialog();
    }
    const handleErrorWebCam = (error) => {
      console.log(error);
    }
    const handleScanWebCam = (result) => {
      if (result){
          setScanResultWebCam(result);
      }
     }
  return (
    <Container className={classes.conatiner}>
          <Card>
              <h2 className={classes.title}>Generate Download & Scan QR Code with React js</h2>
              <CardContent>
                  <Grid container spacing={2}>
                      <Grid item xl={4} lg={4} md={6} sm={12} xs={12}>
                          <TextField label="Enter Text Here" onChange={(e) => setText(e.target.value)}/>
                          <Button className={classes.btn} variant="contained" 
                            color="primary" onClick={() => generateQrCode()}>Generate</Button>
                            <br/>
                            <br/>
                            <br/>
                            {imageUrl ? (
                              <a href={imageUrl} download>
                                  <img src={imageUrl} alt="img"/>
                              </a>) : null}
                      </Grid>
                      <Grid item xl={4} lg={4} md={6} sm={12} xs={12}>
                        <Button className={classes.btn} variant="contained" color="secondary" onClick={onScanFile}>Scan Qr Code</Button>
                        <QrReader
                          ref={qrRef}
                          delay={300}
                          style={{width: '100%'}}
                          onError={handleErrorFile}
                          onScan={handleScanFile}
                        //   legacyMode
                        />
                        <h3>Scanned Code: {scanResultFile}</h3>
                      </Grid>
                      <Grid item xl={4} lg={4} md={6} sm={12} xs={12}>
                         <h3>Qr Code Scan by Web Cam</h3>
                         <QrReader
                         delay={300}
                         style={{width: '100%'}}
                         onError={handleErrorWebCam}
                         onScan={handleScanWebCam}
                         />
                         <h3>Scanned By WebCam Code: {scanResultWebCam}</h3>
                      </Grid>
                  </Grid>
              </CardContent>
          </Card>
    </Container>
  )
}
const useStyles = makeStyles((theme) => ({
    conatiner: {
      marginTop: 10
    },
    title: {
      display: 'flex',
      justifyContent: 'center',
      alignItems:  'center',
      background: '#3f51b5',
      color: '#fff',
      padding: 20
    },
    btn : {
      marginTop: 10,
      marginBottom: 20
    }
}));

export default YoutubeQrcode`



Uncaught TypeError: Cannot read properties of null (reading 'openImageDialog')  im facing this issue
