### ISSUE TITLE
Component always throws exception in case of unload after successful scan

### ISSUE THREAD

**Issue by kreig** [JodusNodus/react-qr-reader#24]
Example code:

    class Test extends React.Component {
        state = { value: null }
        onValueScanned: function(data) {
            this.setState({ value: data });
        }
        render() {
             if (this.state.value) return <span>Scanned: {this.state.value}</span>
             return <ReactQrReader onScan={data=>this.onValueScanned} />
        }
    }

Throws `Cannot read property 'videoWidth' of null` exception after successful scan.

Of course it can be fixed with simple workaround:

    <ReactQrReader onScan={data=>setTimeout(()=>this.props.onValueScanned(data), 50)} />

But it would be better to check if component is still loaded after `onScan` callback invocation.

**Comment by JodusNodus** [comment]
👍 Thanks! I found the problem. I will fix this tonight and publish the new version.

**Comment by kreig** [comment]
Thank you for ultra-fast feedback :smiley:

**Comment by JodusNodus** [comment]
Fix published in 1.0.5

**Comment by iamnomana** [comment]
This issue still exist in version 2.2.1.
How do I fix it
NB: I'm using Next.Js
