### ISSUE TITLE
Loading Method for Component State

### ISSUE THREAD

**Issue by DannyLingard** [JodusNodus/react-qr-reader#25]
Is it possible to have a method made available while the Reader is loading/initializing? I assume it takes a bit to fire up WebRTC etc so just hoping to be able to mount a loading component in the interim. I'm Developing on a Dell Latitude E7470 (i7, 16GB RAM) and it takes the reader 20-50ms to load after mounting, so imagine it would possibly be longer on a phone. Thanks

**Comment by JodusNodus** [comment]
Yes that would be nice indeed. Should be simple so i’ll add it today.

**Comment by JodusNodus** [comment]
In 1.1.0 `onScan` and `onError` behaviour has changed as well so check out the README.
