### ISSUE TITLE
Class Prop

### ISSUE THREAD

**Issue by DannyLingard** [JodusNodus/react-qr-reader#26]
Is it possible to have a class/className prop? This will tidy up layouts by reducing the need for a container <div> for CSS. Also, I'm building a legacyMode view and it would be good to have it as a direct sibling selector.

**Comment by JodusNodus** [comment]
👍 Gonna add that the next release. Have todo some work anyway.

**Comment by JodusNodus** [comment]
Going to release the next version soon. (Changelog will show up in releases from now on 👍  )
