### ISSUE TITLE
How to implement new ViewFinder - Instructions Unclear

### ISSUE THREAD

**Issue by ShiftyKitty** [JodusNodus/react-qr-reader#265]
Looking for ViewFinder to be implemented on QR code reader but docs don't adequately demonstrate how to use. 

Previously showViewFinder accepted a Boolean value, which makes sense whether you want to switch on or off. 

It is now a component but if used as such and attempt to import from "react-qr-reader" this does not work. 

I see that in the working example, a function is passed into this but what information is needed exactly in the function to get this to work and overlay on the video?

Of course can implement my own custom CSS but it seems that this should not be necessary.

**Comment by pinguluk** [comment]
![image](https://user-images.githubusercontent.com/16257821/178777695-ee0ef359-d61d-46d9-b47f-f114d92ba64a.png)
![image](https://user-images.githubusercontent.com/16257821/178777730-0d9e0e6f-bb72-4f83-a536-8e6550471b6e.png)

ViewFinder is a property of QrReader and you pass a component in it, inline like how I did in the screenshots or create a separated component file, place the code, then import and pass it to ViewFinder.
ViewFinder will act as an overlay for the video and further you'll have to modify the css of the component (position: absolute, top: 0, left: 0 etc)

**Comment by pinguluk** [comment]
Here I put the component into a file
![image](https://user-images.githubusercontent.com/16257821/178780214-3d3a11ee-e877-4714-b1df-2b0935dd4c76.png)
![image](https://user-images.githubusercontent.com/16257821/178780263-07ee4e55-e83d-4b4a-a6d6-6489aa87d772.png)
![image](https://user-images.githubusercontent.com/16257821/178780310-47b67ef4-a1cd-467c-8dba-993c4d94f446.png)
