### ISSUE TITLE
onScan firing based on delay

### ISSUE THREAD

**Issue by DannyLingard** [JodusNodus/react-qr-reader#27]
I've updated to 1.1.0 and my onScan() event is firing continuously, passing a null data object. It's still recognizing the delay (ms or false). I added an early exit for !data so it still works for legit scans but just checking if this is intended.

**Comment by JodusNodus** [comment]
Yes this is intended check out the README.

**Comment by DannyLingard** [comment]
Sorry never re read the onScan() as didn't realise it'd changed 😬

**Comment by JodusNodus** [comment]
Yeah sorry my fault. I should start creating a changelog next update.
