### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by DannyLingard** [JodusNodus/react-qr-reader#30]
Cheers for the work in regards to performance and speed improvements in the new version. Was wondering if there's any opportunities to reduce the bundle size as it's > 470KB (not 
 compressed or minified) in my webpack bundle?

Without knowing a lot about jsQR, does it provide the functionality to both encode and decode? If so, would it be feasible to spin off any unnecessary code not required in scanning/decoding of QR Codes into an additional package?

**Comment by JodusNodus** [comment]
jsQr does not provide encoding functionality, the bundle size is currently ~48KB.

**Comment by JodusNodus** [comment]
Check out the new release `1.1.3` its bundle size is greatly reduced compared to `1.1.2`
