### ISSUE TITLE
Not working on android google chrome

### ISSUE THREAD

**Issue by NijsJonas** [JodusNodus/react-qr-reader#304]
this qr reader works fine on my computer but not on my android oneplus phone.
i open my app using a google chrome browser, it loads the app fine, but i dont see my camera and i dont get the popup to allow my camera

**Comment by sosnoski** [comment]
I had the same problem a few days ago. tried the online example in the docs and it was working, so I tried with a self signed certificate in my local environment (https://localhost) and this solved it. I think this is something like browser policy. Hope this help you
