### ISSUE TITLE
Android Chrome: facingMode="rear" on first visit

### ISSUE THREAD

**Issue by Archheretic** [JodusNodus/react-qr-reader#31]
First time a user opens the page with the qr-reader the front camera will be used instead of the rear camera. However on refresh and future visits the rear camera will be used. 
Render code used:
`           
             <div className="QRScanner">
                <QrReader
                    delay={this.state.delay}
                    style={previewStyle}
                    onError={this.handleError}
                    onScan={this.handleScan}
                    facingMode="rear"
                />
                <p>{this.state.result}</p>
            </div>
`

**Comment by JodusNodus** [comment]
Is this only a problem in Chrome on android?

**Comment by Archheretic** [comment]
I have no iPhone or Windows Phone to test Chrome on.
I did test some other browsers on Android: 
 - Samsung Internet browsers worked flawless with back camera.
 - Opera will prompt the user just like Firefox regarding if they want to use rear or front 
   camera. 
 - Opera mini will not work at all (perhaps it will work with legacy mode).

**Comment by JodusNodus** [comment]
Hmm, yeah I never tested opera mini.  I'll do some testing on Android chrome tommorow

**Comment by JodusNodus** [comment]
I did some testing and i was able to reproduce this. Unfortunately there is no simple fix as this is a problem in the spec. I did a hacky fix meanwhile that should fix it in most cases.
[https://bugs.chromium.org/p/chromium/issues/detail?id=290161](https://bugs.chromium.org/p/chromium/issues/detail?id=290161)
