### ISSUE TITLE
The facingMode: "rear" is not working in chrome android 

### ISSUE THREAD

**Issue by Foxhound401** [JodusNodus/react-qr-reader#34]
The front camera is always used, no matter how i set the facingMode. and this is how i render my component
<QrReader
                      delay={this.state.delay}
                      style={previewStyle}
                      onScan={this.handleScan}
                      onError={this.handleError}
                      facingMode="rear"
                  />

**Comment by JodusNodus** [comment]
Can you please show a code snippet because the facingMode works as it should on my android device with chrome. Have you tested it out on the [demo](https://thomasbilliet.com/react-qr-reader)?
