### ISSUE TITLE
MediaDevices API has no support for your browser. You can fix this by running "npm i webrtc-adapter"

### ISSUE THREAD

**Issue by 4d4ch4u32** [JodusNodus/react-qr-reader#354]
Hello, I'm using the `react-qr-reader` in a combination of these packages:

```
"@popperjs/core": "^2.11.6",
"bootstrap": "^5.1.3",
"isomorphic-fetch": "^3.0.0",
"isomorphic-unfetch": "^3.1.0",
"jwt-decode": "^3.1.2",
"next": "12.1.4",
"next-i18next": "^10.5.0",
"react": "17.0.2",
"react-bootstrap": "^2.2.3",
"react-bootstrap-icons": "^1.10.2",
"react-dom": "17.0.2",
"react-i18next": "^11.16.2",
"react-qr-reader": "^3.0.0-beta-1",
"webrtc-adapter": "^8.2.3"
```

In my local dev environment (localhost) and production on localhost, the qr reader works, but not in production on the server. I see the message `MediaDevices API has no support for your browser. You can fix this by running "npm i webrtc-adapter"` in the dev console.

Tested with firefox and google chrome.

Any ideas why?

**Comment by fippo** [comment]
getUserMedia requires a secure context, i.e. https as you found out on stackoverflow.

@JodusNodus it would probably be better to link to https://developer.chrome.com/blog/chrome-47-webrtc/ instead of recommending webrtc-adapter which can't magically fix this ;-)

**Comment by 4d4ch4u32** [comment]
Using `webrtc-adapter` has not fixed the problem. But yes, it works on a server with https.

**Comment by 4d4ch4u32** [comment]
Yes, that's right, after I deployed it to a setup with https, it works.

See also https://stackoverflow.com/questions/76679271/mediadevices-api-has-no-support-for-your-browser-if-not-localhost
