### ISSUE TITLE
Blob undefined

### ISSUE THREAD

**Issue by wiredots01** [JodusNodus/react-qr-reader#36]
`ReferenceError: Blob is not defined
    at Object.<anonymous> (/Users/wiredots/Projects/new/reactproject/node_modules/react-qr-reader/lib/index.js:26:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value`

**Comment by JodusNodus** [comment]
Can you give more details please? What is the environment (browser, nodejs, unit test) etc

**Comment by wiredots01** [comment]
chrome, node 6.11.2, jest, mac, using arc base react

**Comment by JodusNodus** [comment]
Check this https://github.com/JodusNodus/react-qr-reader/issues/35

**Comment by JodusNodus** [comment]
Let me know if that fixes it

**Comment by wiredots01** [comment]
dont have problems on test.
when i run the app it stops on this
<img width="763" alt="screen shot 2017-09-04 at 8 02 17 pm" src="https://user-images.githubusercontent.com/4254904/30025670-243ff53e-91ac-11e7-9e18-66dbb17b8414.png">

**Comment by JodusNodus** [comment]
Are you trying to server render it ?

**Comment by wiredots01** [comment]
nope.. im using react-qr-reader on the client

**Comment by JodusNodus** [comment]
What is your bundle build pipline?

**Comment by wiredots01** [comment]
i think you are right, there is something on the server rendering that includes the react-qr-code. thanks a lot.

**Comment by RachelAntion** [comment]
How did you resolve this? I'm running into the same issue.

**Comment by tomy8910** [comment]
Same here, using it in electron with next.js, whenever I refresh the main window, the error appears

**Comment by JodusNodus** [comment]
The module uses many things that are browser specific. I'm not familiar with next.js but you should be able to avoid rendering it server side.

**Comment by JodusNodus** [comment]
@RachelAntion Just shallow render your components, or conditionally render it or a placeholder based on the environment (node or browser).

**Comment by powderham** [comment]
@JodusNodus can you give me an example of conditional rendering in react using the environment?

**Comment by wiredots01** [comment]
ive made a condition  `if(!config.isServer) { var QrReader = require('react-qr-reader'); }`
