### ISSUE TITLE
facing Mode does not allow to use rear camera for iOS11.

### ISSUE THREAD

**Issue by rajatvarade-tudip** [JodusNodus/react-qr-reader#37]
I just made our client test the other day with their iPhone and the QR Reader was working but with front camera.

We tried setting the facing mode to 'rear' but it was still using front camera

The iPhone was on iOS 11 and we tested both Safari and Chrome.

Any idea ?

**Comment by JodusNodus** [comment]
Sadly i don't have an iPhone to currently test it on. Probably something wrong with the listed devices available to use. If you want to help provide the following deviceIdChooser. Remote debug using chrome and post the output.

```js
function deviceIdChooser(filteredDevices, videoDevices, facingMode) {
  console.log(videoDevices)
  return videoDevices[1].deviceId
}
```

**Comment by frinko** [comment]
I just updated my iPhone 5s today to iOS 11.0.1 (from iOS 11.0) and both the front and rear camera selections correctly switch, display, and decode for me in Safari. Interestingly, I cannot get the demo site to work on Chrome for iOS as far as using the cameras - it defaults to legacy, but that could just be the demo site's configuration, etc. I love that webkit now supports WebRTC!

**Comment by JodusNodus** [comment]
Yes finally support across platforms! @frinko Could you try out my instructions in my first response to this issue?

**Comment by frinko** [comment]
@JodusNodus Yes I will try that out and post the logs. When I saw this issue posted, I just tried while using the demo site because I knew that my phone had recently updated to the newer iOS version which was supposed to include the WebRTC support inside of webkit.

**Comment by TheWildHorse** [comment]
Same problem here. Any luck @frinko ?

**Comment by n8io** [comment]
@JodusNodus The output I am seeing has two devices with unchanging IDs, however the order of the id's being returned is not always the same.

```js
...
  "filteredDevices": [],
  "videoDevices": [
    {
      "deviceId": "F2EF6FA859E5BF554BEB52FF4CD11A57813DA14E",
      "kind": "videoinput",
      "label": "",
      "groupId": ""
    },
    {
      "deviceId": "621CC1DA97607D5E6DDC1BCCA918419DD4D725C5",
      "kind": "videoinput",
      "label": "",
      "groupId": ""
    }
  ]
...
```

**Comment by JodusNodus** [comment]
@n8io Thanks alot! Seems that the problem is that webkit on IOS does not provide labels. Which i use for choosing the facingMode. I don't use the `facingMode` option in `getUserMedia`because choosing the device manually gives me more consistent results accros browsers. Seems like i will have to make an exception for IOS Safari 🤦‍♂️.   Safari on mac works fine.

**Comment by athyuttamre** [comment]
Strangely both cameras work for me on iOS 11 on the demo site, but when I copy-paste the demo-site code to my own site, only the front camera works. I'm pretty confused as to why this might be the case.

**Comment by athyuttamre** [comment]
I debugged this a little bit. My environment is Safari on iOS 11.1 (15B5066f) on an iPhone 6s.

It looks like the response to `navigator.mediaDevices.enumerateDevices()` changes depending on whether or not the user has given permission to the website to access the devices.

When it is called in `getDeviceId()`, *before the user has given their permission*, the response is something like this:

```
[  
   {  
      "deviceId":"FF7FE1B777981878FE764FCBCB51FA7BB0096E9C",
      "kind":"audioinput",
      "label":"",
      "groupId":""
   },
   {  
      "deviceId":"A18607B2B11F842DCAD5DF278AA227E315FBA807",
      "kind":"videoinput",
      "label":"",
      "groupId":""
   },
   {  
      "deviceId":"B82973FC74E4024B7E59AB229CDB1968D4BA9B6B",
      "kind":"videoinput",
      "label":"",
      "groupId":""
   }
]
```

However, once the user has given their permission (i.e. `getUserMedia` was called, and the user approved), if you connect your iPhone to Safari and call `navigator.mediaDevices.enumerateDevices()` again, the response is something like this:

```
[  
   {  
      "deviceId":"F739A7B0AFBE13E7C11BBDD5EA1CA6359287244D",
      "kind":"audioinput",
      "label":"iPhone Microphone",
      "groupId":""
   },
   {  
      "deviceId":"9F24387DF50E28745ACA95DC41247E749918B848",
      "kind":"videoinput",
      "label":"Back Camera",
      "groupId":""
   },
   {  
      "deviceId":"562B31EE4CFB8B883B1AA6A4C98474B681C0B4F5",
      "kind":"videoinput",
      "label":"Front Camera",
      "groupId":""
   }
]
```

Thus, our code fails because the labels aren't provided until user has granted permission. The trick I suppose is to ask the user for permission on one of the video devices. Then call `enumerateDevices()` again, and pick the right one.

In addition, I also noticed that for our code to work with the new labels, our pattern test will need to be updated (https://github.com/JodusNodus/react-qr-reader/blob/master/src/getDeviceId.js#L43).

It is currently:

```
const filteredDevices = videoDevices.filter(({ label }) => pattern.test(label))
```

We should test on lowercase `label`, and thus it should be:

```
const filteredDevices = videoDevices.filter(({ label }) => pattern.test(label.toLowerCase()))

```

**Comment by athyuttamre** [comment]
Note that the device IDs change on each invocation of `enumerateDevices`. Presumably this is to prevent fingerprinting of users.

**Comment by athyuttamre** [comment]
Actually, perhaps a better solution, as @JodusNodus referenced, is to use the option in `getUserMedia`. 

Perhaps we can feature detect to see if `navigator.mediaDevices.getUserMedia` is available, and if so, use it's API to detect `front` and `rear`?

The presences of the newer `navigator.mediaDevices.getUserMedia`, as opposed to the older `navigator.getUserMedia`, suggests that the newer API is supported and the browser is sufficiently modern to give reliable results.

**Comment by JodusNodus** [comment]
@athyuttamre Thanks a lot for doing the digging! This permission issue has been irritating me for a long time now. It also causes not being able to pick the right device on first load. Indeed i would need to preload a random device to request the permissions and then request the available devices. The filtering doesn't need to change as the regex pattern uses the case insensitive flag.
By specifying the device ID i am able to work around many bad browser `facingMode` implementations (or the lack of). It also allows the user to choose the device.
If this doesn't work i'll have to use the the actual `facingMode` API in the newer `getUserMedia` but the permission issue would still exist for older implementations.

**Comment by athyuttamre** [comment]
@JodusNodus thanks for the quick follow-up! I'm still learning the API and this codebase, so sorry for not catching that the regex was actually correct.

Any thoughts on using this polyfill (https://github.com/webrtc/adapter) and simply sticking to the new API? Or, if you have a list of older browsers where the new API fails, perhaps we should special case them?

According to MDN, looks like the new API is supported pretty deep on most browsers: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Browser_compatibility.

**Comment by athyuttamre** [comment]
Ah, I see what you mean by the permission issue still existing in older browsers. I think it might be useful to ensure support for newer browsers, and then in time adding support for older ones? We can leave a note in the README saying that if you require older browser support in the meantime, please don't upgrade.

**Comment by JodusNodus** [comment]
@athyuttamre No problem!
I already use that polyfill. It does a pretty good job but it ain't perfect. The problem even occurred in Chrome a couple versions ago. Browsers would throw `OverconstrainedError`.  Sadly i don't have a list of browser support.

I'm going to experiment with some stuff and see what would best solve this problem.

**Comment by athyuttamre** [comment]
Ah, I see! And awesome, thank you for looking into this. Happy to help in any way I can, just let me know.

**Comment by JodusNodus** [comment]
@athyuttamre Could you try out the new `ios11-fix` branch on IOS? It creates a temporary media stream to get permissions. It works on chrome android and desktop. Firefox doesn't follow `deviceId` or `facingMode` constraints so it is ignored.

**Comment by TheWildHorse** [comment]
For some reason while using ios11-fix branch Safari on OS X or iOS 11 don't ask for camera permissions at all.

**Comment by JodusNodus** [comment]
@TheWildHorse Issue with the constraints. Fixed it. Works on Safari OSX.

**Comment by TheWildHorse** [comment]
@JodusNodus Hmm, this seems to break my app on all platforms, including OSX. :/

**Comment by JodusNodus** [comment]
@TheWildHorse Any error logs? Because i updated the demo to use it and hosted it here https://vengeful-spark.surge.sh It works on all browsers on mac and android that i have tested.

**Comment by TheWildHorse** [comment]
@JodusNodus Testing it now, will let you know!

**Comment by TheWildHorse** [comment]
@JodusNodus It works, but still does not allow me to use the rear camera on iOS 11. This is how I call the QrReader (using the latest revision of the ios11 branch) and the front camera opens up.

`<QrReader
                    style={style}
                    facingMode="rear"
                    onError={this.handleError}
                    onScan={this.handleScan}
                />`

**Comment by TheWildHorse** [comment]
The actual filtering works fine, the back camera gets filtered and selected for the permission access request. Not sure where it goes downhill from there...

![](https://i.imgur.com/XmpIDOE.png)

**Comment by JodusNodus** [comment]
@TheWildHorse thanks for doing the testing. Haven't been able to work on it. I'll try to mock it here and see where it breaks.

**Comment by TheWildHorse** [comment]
@JodusNodus  Found the problem, and made a hotfix for my purposes. Feel free to tidy it up and include it in the master: https://github.com/JodusNodus/react-qr-reader/pull/40

Not sure if the "exact" syntax works everywhere so I just made it trigger on iOS devices.

**Comment by JodusNodus** [comment]
@TheWildHorse Great. Seems like using `exact` also gets around the Firefox problem (ignoring deviceId en letting the user choose with a native dialog). I'll test it out accros browsers to see what the support is. If it doesn't cause regression i will just make it the default. Otherwise an exception for firefox and IOS like your PR

**Comment by n8io** [comment]
@JodusNodus any progress on this? Love the work so far btw.

**Comment by JodusNodus** [comment]
@n8io Thanks, no i haven't had much time to work on this as i am a student and this is a side project. This weekend i should be able to spend some time on it.

**Comment by TheWildHorse** [comment]
@n8io Feel free to contribute your time! :)

**Comment by JodusNodus** [comment]
Hey i updated the `ios11-fix` branch with a lot of changes and improvements. Works on firefox android & macOs, chrome android & macOs, and Safari macOs. Can somebody please test IOS out?

**Comment by zeusbangayan** [comment]
not working on ios11.. stuck on rear camera

**Comment by JodusNodus** [comment]
@zeusbangayan Weird, does it throw any errors? Could u try the demo bellow too.
https://react-qr-reader.surge.sh

**Comment by jjperezaguinaga** [comment]
👋  @JodusNodus I can confirm that https://thomasbilliet.com/react-qr-reader/ works on my iPhone 6 w/iOS 11, will test now the branch directly, thanks!!

**Comment by zeusbangayan** [comment]
im using iPhone 7 Plus. would that make a difference?

**Comment by JodusNodus** [comment]
@zeusbangayan I don't see why it would make a difference. No clue what is the problem. Are there any errors thrown?

**Comment by JodusNodus** [comment]
I can confirm that it works on ios. So i will publish version 2.0.0

**Comment by rajivramv** [comment]
When are you rolling out 2.0.0?

**Comment by JodusNodus** [comment]
@rajivramv Already on NPM.
