### ISSUE TITLE
Does the library work in an Android Cordova app?

### ISSUE THREAD

**Issue by PositronicBrain** [JodusNodus/react-qr-reader#38]
I tried and it does not seem to work, but I haven't found any explicit reference in the documentation whether the Cordova platform is supported.

**Comment by JodusNodus** [comment]
I never tried that. It seems like this is a problem with cordova. As you can actually use the `getUserMedia` API in modern webviews.

http://www.flapjacksandcode.com/blog/2015/2/17/android-webviews-getusermedia-putting-it-all-together
https://github.com/apache/cordova-android/pull/178
