### ISSUE TITLE
Need ability to set deviceId

### ISSUE THREAD

**Issue by kybarg** [JodusNodus/react-qr-reader#43]

**Comment by JodusNodus** [comment]
Versions before 2.0.0 used the deviceId to choose the camera and it also allowed to supply a custom deviceId chooser. But this broke compatibility with iOS and caused a couple of other problems. So that isn't possible anymore.

**Comment by kybarg** [comment]
@JodusNodus there are ways to detect device and apply custom rules. Such functionality would be useful in browser

**Comment by JodusNodus** [comment]
Yes but the problem with detecting the device was that it didn't supply everything needed before first permission request which is made on launching the camera.

**Comment by JodusNodus** [comment]
The goal of this project is not to be the most extensible and customisable QR-code reader. It is to provide a simple component that you can place in any React app. If require more control i would suggest looking at https://github.com/schmich/instascan .
