### ISSUE TITLE
Does not work on iOS Chrome browser

### ISSUE THREAD

**Issue by stevenihan** [JodusNodus/react-qr-reader#45]
**Specification:**
- iPhone SE
- iOS 11.1.1
- Chrome 62.0.3202.70

**Screen shot from iPhone**
- <img width="250" alt="screen shot from iPhone" src="https://user-images.githubusercontent.com/12016692/32816839-60234b22-c9ed-11e7-9460-88aa4c964437.png">

**Screen shot from sentry report**
- <img width="1006" alt="sentry report" src="https://user-images.githubusercontent.com/12016692/32816965-f4111bac-c9ed-11e7-9d27-f866da08b79e.png">

**Comment by JodusNodus** [comment]
Thanks for reporting the issue it seems like the mediaDevices API is private in webkit IOS and thus only works on Safari IOS. I'll add it to the README.

https://bugs.chromium.org/p/chromium/issues/detail?id=752458

**Comment by stevenihan** [comment]
Hi @JodusNodus,

Can you add validation like;
```
var supportedConstraints = navigator.mediaDevices !== undefined ? navigator.mediaDevices.getSupportedConstraints() : {};
```
so it will not throw error exception and my code is running well with legacyMode value is true.
Thanks!

**Comment by JodusNodus** [comment]
@stevenihan Yup, i'll add it.

**Comment by JodusNodus** [comment]
I'll publish it in `2.0.1`. In the meanwhile you can use the git repo directly.

**Comment by JodusNodus** [comment]
Version `2.0.1` has been published

**Comment by stevenihan** [comment]
Nice. Thank you! @JodusNodus

**Comment by zeusbangayan** [comment]
did it work for you @stevenihan? not working on me..

**Comment by zeusbangayan** [comment]
also on Chrome MACOS High Siera

**Comment by stevenihan** [comment]
yes, it's work for me. I just enable `legacyMode` when there is an error from `react-qr-reader`.
please send your debug result; so the author can investigate it. @zeusbangayan
