### ISSUE TITLE
facingMode: Inconsistent behaviour on different devices

### ISSUE THREAD

**Issue by sensotix** [JodusNodus/react-qr-reader#46]
Great package! One issue, though, with regards to facingMode. On smartphones, facingMode flips between front and rear cameras. I figured that on desktops with just a single camera the facingMode flips between original and mirrored image. Is it possible to decouple these two features into separate properties? I tested with various people and a lot of them get confused when they see themselves mirrored and try to zoom in on the QR-part when using environment-facingMode. On smartphones everything is fine. But user-facingMode is not an option since it would activate the (often lower resolution) front camera on mobile devices. Thanks!

**Comment by JodusNodus** [comment]
@sensotix Indeed, that is pretty anoying. I could do it by assuming that if there is only 1 videodevice it means that only an user facing camera exists.

**Comment by sensotix** [comment]
Sure that would work I guess! Thank a lot!

**Comment by JodusNodus** [comment]
@sensotix Could you try it out to see if it works for you?

**Comment by sensotix** [comment]
@JodusNodus Works great now, thanks! Can you deploy to npm please?

**Comment by JodusNodus** [comment]
@sensotix Great, I have published `2.0.1` on npm.
