### ISSUE TITLE
Doesn't pick rear camera on Android Chrome

### ISSUE THREAD

**Issue by jerefrer** [JodusNodus/react-qr-reader#5]
When going on the demo page with Android Chrome 51.0.2704.81, the front camera gets picked by default. There is no prompt for choosing the camera as there is on latest Android Firefox.
I'm using Android 4.2.2 on a FairPhone 1.

It seems it's possible to select the rear one, as I'm able to do it on https://webrtc.github.io/samples/src/content/devices/input-output/ through the select input.

**Comment by JodusNodus** [comment]
I have edited it so that it forces the facingMode (not just prefer it) if provided otherwise it will let the browser choose (on some browser it shows an alert on some it doesn't like chrome for android). I will publish this update as soon as possible.

**Comment by JodusNodus** [comment]
It also seems that their are inconsistencies with constrains on chrome vs the standard.

**Comment by JodusNodus** [comment]
I have updated the module to 0.2.8. Please test the demo again.

**Comment by jerefrer** [comment]
Just tried.

Even though I choose "Back" from the select, the video output keep displaying from the front one.

Shouldn't "back" be "rear" to be picked up correctly ? Seems like so looking at the commit.

**Comment by jerefrer** [comment]
After having updated and tried on my own app where I set `facingMode` to `rear`, the rear camera gets properly picked up, and then it recognizes the QrCode !

So it seems it's working fine now on Android Chrome !

**Comment by JodusNodus** [comment]
👍 Sorry the demo used the value `back` for facingMode instead of `rear`. I have corrected that.
