### ISSUE TITLE
Facebook 'in-app' browser

### ISSUE THREAD

**Issue by NataliaMaurizio** [JodusNodus/react-qr-reader#50]
**[QUITE URGENT]**

Hello,
I'm not able to use this library on the **Facebook 'in-app' browser**. This happens when I open the link from a chat in **Messenger**.

- Do you have an idea of ​​why?
- Do you know any workarounds in order to avoid this problem?

Thank you so much! 👍

**Comment by JodusNodus** [comment]
Sorry but it seems you left some information out. What happens when you open it in the in-app browser?

**Comment by NataliaMaurizio** [comment]
Yes, when I open the link in the in-app browser It does not require the camera access and the square camera remains closed/blocked. 
Try to check out your demo link from your messenger, your page remains “loading”...

**Comment by JodusNodus** [comment]
What version are you using?

**Comment by NataliaMaurizio** [comment]
When I try to execute the command `npm install --save reacr-qr-reader`, I get:

- `npm WARN react-qr-reader@2.0.1 requires a peer of react@^15.0.2 but none is installed. You must install peer dependencies yourself.`

- `npm WARN react-qr-reader@2.0.1 requires a peer of react-dom@^15.0.2 but none is installed. You must install peer dependencies yourself.`

`+ react-qr-reader@2.0.1`
`added 5 packages in 10.737s`

**Comment by NataliaMaurizio** [comment]
It seems like I've some dependency missing...
My `package.json` has

- react: "^16.1.1"
- react-dom: "^16.1.1"

Probably have I to downgrade these two dependencies?

**Comment by NataliaMaurizio** [comment]
Unfortunately, I've the `react` and `react-dom` updated to the version *16.1.1*

**Comment by JodusNodus** [comment]
@NataliaMaurizio yeah i should update those peer deps. That shouldn't be the problem. I currently don't have the time to dive deep in to this. But it would be nice if you could get the error logs.

**Comment by NataliaMaurizio** [comment]
Sure, buy I've not an `error logs`. It seems like Facebook blocks web camera access... 👎 
Ok, I'll try to use another lib in order to going on with my work :)

Thank you so much

**Comment by NataliaMaurizio** [comment]
Sorry, Have you solved this problem?

**Comment by NataliaMaurizio** [comment]
Hello there,

I would to know if you were able to solve this issue :)

Thank you so much

Maurizio Natalia

2017-12-01 11:27 GMT+01:00 Thomas Billiet <notifications@github.com>:

**Comment by JodusNodus** [comment]
If facebook in-app browser blocks web camera API then there is nothing i can do.
