### ISSUE TITLE
Ability to stop the scanner and start it back again

### ISSUE THREAD

**Issue by Jordan4jc** [JodusNodus/react-qr-reader#51]
I have this implemented as a ticket scanner for our event managment software platform. It would great and is super quick, but we've noticed over time the phone starts to get a little warm, we assume this is because of the always on nature of the qr scanner.

I would love a way to be able to stop the scanner after we've scanned something and start it back up when we're ready to scan the next ticket.

I was able to kind of get this working by wrapping the `<QrReader />` in a conditional in my state and that seemed to work well enough, however I kept getting an error in the console that seemed like it wasn't liking the fact that I had it in a conditional

Specifically this error

```
TypeError: Cannot read property 'srcObject' of null
    at Reader.handleVideo (index.js:206)
    at <anonymous>
```

**Comment by frinko** [comment]
@Jordan4jc I have the qr-reader implemented as a separate route (e.g. with react-router) and this always takes care of the camera starting and stopping. I have also used other libraries that interact with the user's camera and most of them recommend redirecting to a new path in order to ensure the camera stream stops.

**Comment by JodusNodus** [comment]
@Jordan4jc Weird error, are you running the latest version? Another solution that would be more performant is to hide the scanner with css & setting the `delay` prop to `false` (This disables the scanning).

**Comment by fridezlucas** [comment]
+1, Is it possible to implement the possibility to turn off the camera and turn on later ?

**Comment by quickshiftin** [comment]
+1 - Same problem here. I'm using the scanner on one page, then upon successful scan, redirecting (client side) to another page. Something is not getting cleaned up with the scanner though, even though it's been unmounted.

The [`handleVideo`](https://github.com/JodusNodus/react-qr-reader/blob/master/src/index.js#L165) function is still being run repeatedly by `setTimeout` and my browser still indicates the camera is in use (by looking in the tab at the top of the browser, there is a red circle).

**Comment by JodusNodus** [comment]
Should be fixed in the upcoming release. Let me know if you still have problems.

**Comment by avichovatiya67** [comment]
I have the same issue, where the scanner keeps on scanning and not waiting for the data to be stored in the database, even before the data reaches to Database, it sends new events and we have a duplication.

we tried adding timeout at onResult and other approaches but not working. 

is there any quick solution? @JodusNodus
