### ISSUE TITLE
React-qr-reader and Cordova

### ISSUE THREAD

**Issue by juliopiubello** [JodusNodus/react-qr-reader#55]
Hello !

is it possible to make it work on cordova ? Used the component in my app and didn't want to changed it

**Comment by juliopiubello** [comment]
or why it does not work after cordova ?

**Comment by JodusNodus** [comment]
I haven't tried it. What error do you get?

**Comment by juliopiubello** [comment]
Hello, thx for replying
On mobile works fine at the chrome, safari, and PWA but when I tried to use at cordova:
![image](https://user-images.githubusercontent.com/16126595/35133075-700fce2a-fcb5-11e7-8f59-52c5287b69e6.png)

may u have an idea ? I couldn't figure it out

**Comment by globophobe** [comment]
It’s not clear from the picture. Can you make a sample repo?

**Comment by JodusNodus** [comment]
@juliopiubello Have you added the android camera permission ?

**Comment by juliopiubello** [comment]
Sample repo it's only the component

No, sorry for my ignorance, I tried but it's only clear when I'm doind on react-native
How should I do ? Use a cordova plugin ?

**Comment by juliopiubello** [comment]
Hi, figured it out, I had to use a cordova plugin for asking permission for the camera!

Thank you for the help

**Comment by mehthabt** [comment]
> Hi, figured it out, I had to use a cordova plugin for asking permission for the camera!
> 
> Thank you for the help

hello, can you explain how to do this?

**Comment by juliopiubello** [comment]
@mehthabt it was a long time ago, but I think it was:
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/
