### ISSUE TITLE
How to capture image when onScan found

### ISSUE THREAD

**Issue by kanapan** [JodusNodus/react-qr-reader#57]
i want to save image to base64 when onScan found qr code for send to server.

how should i do?

thx for answer.

**Comment by JodusNodus** [comment]
Sorry for the late response. Here is a working example assuming that you have the reader component ref.
```js
onScan(result) {
  if (result) {
    const canvas = this.refs.reader.els.canvas
    const base64jpg = canvas.toDataURL('image/jpeg')
  }
}
```

**Comment by kanapan** [comment]
thx god !!
