### ISSUE TITLE
QrCodes never recognized on Android Firefox

### ISSUE THREAD

**Issue by jerefrer** [JodusNodus/react-qr-reader#6]
When using Android Firefox 47.0 I got prompted to choose which camera I'd like to use, chose the rear camera, but then when I aim at any QrCode it seems it never get recognized as the "Decoded QR-Code:" output stays on "No result".

When trying with Android Chrome it works and displays the content of the QrCode ([although I can't use the rear camera](https://github.com/JodusNodus/react-qr-reader/issues/5))

I'm using Android 4.2.2 on a FairPhone 1.

Anyway thanks a lot for sharing this component, it's so pleasant when it just (kind of) works.

**Comment by JodusNodus** [comment]
I have just tested this with firefox 47.0 on android 6.0 and it works fine. Sometimes it takes a while to recognise because of lighting or focusing issues but except that it works. Unfortunately it is pretty hard to test all os'es and browsers.

**Comment by JodusNodus** [comment]
I have updated the module to 0.2.8. Please test the demo again.

**Comment by jerefrer** [comment]
Sorry it doesn't work either. It never recognizes the QrCode.

Also even though I choose "back" from the select, the video output keep displaying from the front one.

**Comment by jerefrer** [comment]
After having updated and tested on my on app, it seems that the rear camera gets properly picked up, but I still have the issue about not recognizing the QrCode. I tried focusing on it for a long time from different positions and it never picked it up.

**Comment by JodusNodus** [comment]
I am not able to reproduce your problem with it not recognising the QR code. It is a shame that it is so hard to debug, but is you are willing you could try [debugging over USB](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE). Check if the canvas is in the DOM and if no errors are logged.

**Comment by JodusNodus** [comment]
With the latest release of `react-qr-reader@1.0.2`the heavy work is separated from the DOM process resulting in much better performance. I have tested it with both the latest release of chrome and firefox on android and they work great. Please upgrade and let me know!
