### ISSUE TITLE
On windows and using chrome openImageDialog() does not work

### ISSUE THREAD

**Issue by ChrisWiles** [JodusNodus/react-qr-reader#62]
openImageDialog function does work on windows. Works fine my mac and android phone

``` javascript  
openImageDialog() {
    // Function to be executed by parent in user action context to trigger img file uploader
    this.els.input.click()
}
```

Uncaught TypeError: Cannot read property 'click' of undefined at openImageDialog

**Comment by ChrisWiles** [comment]
Ended up being an issue with legacyMode

**Comment by nxtexe** [comment]
I am having this same problem on Windows. Will it work on iOS? Is it just a case where it only breaks on windows?
