### ISSUE TITLE
Constraints too restrictive/not customizable

### ISSUE THREAD

**Issue by antmarot** [JodusNodus/react-qr-reader#65]
I was getting the `OverconstrainedError` on a smartphone until I got rid of the frame rate's `min` constraint. With that constrain removed, everything worked fine and with an actually good frame rate. It's probably a browser/device bug (e.g. it wasn't working either with a min. frame rate of 1), but I'm not sure why that constraint is required in the first place. Wouldn't it work with any frame rate?

Also, it would be great to have props to override the default constraints.

Nice work btw.

**Comment by mpodlasin** [comment]
I have this problem as well. Bump!

**Comment by rajtrivedi88** [comment]
@adipascu thanks..it started working with the above hack.One issue I found after using the hack is that ,it is exceeding the layout area and overlaps other divs before it.any idea about it?I have attached an image for the same...
![qr_scanner](https://user-images.githubusercontent.com/6735349/42420215-06fcb55e-82e0-11e8-821a-21c2c1f23c1b.jpg)

**Comment by wayfarerboy** [comment]
@adipascu Adding `overflow: 'hidden'` to the styles prop should fix it.
