### ISSUE TITLE
On mobile, QR code not recognised 

### ISSUE THREAD

**Issue by alluster** [JodusNodus/react-qr-reader#67]
Hi @JodusNodus ! Thanks for a great QR reader! Excellent work! 👍 
I'm running into a problem where the image loaded using the `legacyMode` loads the content of the QR to the state nicely on my Mac & Chrome. 

The problem occurs when using iPhone and Chrome. The `legacyMode` works well untill the image is uploaded on the app. The image freezes on the screen and the QR doesn't get read. do you know how to solve this?

My QR reader: 
![image](https://user-images.githubusercontent.com/21972091/37907049-ac487b54-310c-11e8-941f-7d23e2ff333b.png)

Button to invoke QR reader component on App.js
![image](https://user-images.githubusercontent.com/21972091/37907083-bfd9d834-310c-11e8-91ef-17357085562c.png)

**Comment by ChrisSargent** [comment]
Are you actually getting anything in the 'result' variable in handleScan?

**Comment by alluster** [comment]
Actually, troubleshooting resulted in finding out that the problem is with the images taken with the camera after the `legacyMode` is launched. Trying with a good image was actually successful. Now I'm wondering if there is something I can do to fix the capabilities of QR recognition, other the "resolution" which doesn't seem to add much recognition capabilities.

**Comment by GermanKuber** [comment]
I have the same issue, What was the solution ?

**Comment by FabioRamatis** [comment]
I'm having the same issue, some solution?
