### ISSUE TITLE
No longer working on iOS unless user manually updates privacy settings

### ISSUE THREAD

**Issue by amgarrels** [JodusNodus/react-qr-reader#73]
When using the scanner in iOS the camera is not accessible unless the user manually goes into settings and selects Camera & Microphone Access

![image](https://user-images.githubusercontent.com/25381138/38949190-894c705a-42f6-11e8-880c-6b086858d24c.png)

**Comment by brunobraga95** [comment]
have you found a work around for this?

**Comment by lucasverra** [comment]
interested too in this question

**Comment by JodusNodus** [comment]
Indeed on IOS 12.1 it seems to work fine.
