### ISSUE TITLE
iOS Safari Blob Handling

### ISSUE THREAD

**Issue by haraldkrischner** [JodusNodus/react-qr-reader#74]
I had an TypeError on an iPhone 6s with Safari and Chrome. With the help of Google I tried a fix, but I am not too confident that it resolves the error. 

https://github.com/JodusNodus/react-qr-reader/compare/d6ac6638177b695a759b91dabe9c1e73b08c6ff1...4ffbc764155443f8ad3ee977fb4311ab3daf28ac

**Comment by JodusNodus** [comment]
Sorry for the very very late reaction. Thanks for pointing this out. Seems like Blob needs a shim on some platforms. Added this to the codebase. https://gist.github.com/nolanlawson/10340255
