### ISSUE TITLE
Error on remote (AWS EC2) instance without https

### ISSUE THREAD

**Issue by devssh** [JodusNodus/react-qr-reader#78]
The scanner is working on localhost react app. My react app communicates successfully with the server as a cross origin.
But the QR code scanner gives this error and does not work on ec2, even though i'm running react in the same development mode.

name: "NotSupportedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraint: undefined, toString: ƒ

It might be due to create react app being strict on CORS and security, I have ejected but I'm not sure how to proceed, as I don't know which origins I have to allow in your dependency.

Here is another warning just before the error : 
[Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by ChrisSargent** [comment]
Camera access is only allowed over https

**Comment by devssh** [comment]
Ok I was able to get access over https in the meanwhile, so is this issue unsolvable?

**Comment by ChrisSargent** [comment]
It's due to browser restrictions - AFAIK, nothing can be done about it in this module. You can probably use Legacy mode though which allows the user to take a picture with their camera and use it.
