### ISSUE TITLE
facingMode iOS 11.4

### ISSUE THREAD

**Issue by LukeJJones** [JodusNodus/react-qr-reader#80]
Setting facingMode had no effect on my iPhone 7 Plus. I forked the repo and did some digging and found that if I commented out lines 151 - 153 in index.js that dealt with setting the aspectRatio constraint it would work.

I didn't have time to do much digging on why, but I can look into it and maybe come up with a more elegant solution than just commenting that out. aspectRatio is not a constraint that I'm using so my forked version is fine for me but I'm guessing that this is affecting other users as well unless there's just something unique about my iPhone.

Thanks for your work on this module by the way!

**Comment by jordanambra** [comment]
Yes, this is affecting me as well, with an iPad.
