### ISSUE TITLE
Not working on Huawei phones (Android 8.1) using Google Chrome

### ISSUE THREAD

**Issue by shawnrp** [JodusNodus/react-qr-reader#85]
Using Huawei P20 Pro (Google Chrome) and on the demo website (thomasbilliet.com/react-qr-reader), it shows as webcam not supported. Tested on another Samsung Galaxy Phone on Google Chrome as well, and it works. Does anyone have a fix?

**Comment by LLLLuca** [comment]
Same for me with HUAWI Mate 10 lite

**Comment by JodusNodus** [comment]
Issues on specific devices are out of the scope of this module. Browsers have the same API across devices on a platform so this has to do with device support for browser features.
