### ISSUE TITLE
Where is the code of the demo?

### ISSUE THREAD

**Issue by daldoy** [JodusNodus/react-qr-reader#86]
Where is the code of this demo https://thomasbilliet.com/react-qr-reader/ ?

**Comment by mathewkeene22** [comment]
Hey @JodusNodus, is the code in the gh-pages branch the same as the demo? It seems to work fine on iOS 11 with chrome. I'd love to see the demo code if you have it available. I've been struggling to get the legacy mode to work for my app. Thanks!

**Comment by daldoy** [comment]
> Hey @JodusNodus, is the code in the gh-pages branch the same as the demo? It seems to work fine on iOS 11 with chrome. I'd love to see the demo code if you have it available. I've been struggling to get the legacy mode to work for my app. Thanks!

Yes, the code of the demo is in the gh.pages branch. I asked him on twitter.
