### ISSUE TITLE
Get Image read

### ISSUE THREAD

**Issue by misterfifi1** [JodusNodus/react-qr-reader#87]
Hi, 

is it possible to retrieve the image (base64 encoded) when the scan is successful? 

Regards,

**Comment by JodusNodus** [comment]
When you get the image load event `evt.target.currentSrc` gives you the url which is encoded base64 image.

**Comment by misterfifi1** [comment]
Hi, 
Sorry, but according to the documentation, the "onImageLoad" event is available only for legacy mode. but we are not using this mode. 
Regards,
