### ISSUE TITLE
Get image read from scan (not in legacy mode)

### ISSUE THREAD

**Issue by misterfifi1** [JodusNodus/react-qr-reader#89]
Sorry, but according to the documentation, the "onImageLoad" event is available only for legacy mode. but we are not using this mode. 
Regards,

_Originally posted by @misterfifi1 in https://github.com/JodusNodus/react-qr-reader/issues/87#issuecomment-427760315_

**Comment by JodusNodus** [comment]
Well you can just get the image from the canvas at onScan. Just checkout the HTML5 canvas documentation.

**Comment by JodusNodus** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by misterfifi1** [comment]
perfect thanks

**Comment by evenfrost** [comment]
@JodusNodus `onScan` returns already decoded value, how can I get canvas from it to transform to actual image?
