### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by gdromero** [JodusNodus/react-qr-reader#9]
node_modules/md-gum-polyfill/mediaDevices-getUserMedia-polyfill.js:36
[2] })();
[2]   ^

ReferenceError: navigator is not defined

I have this issue when compile my application.

**Comment by gdromero** [comment]
Whe I remove the parenthesis, its works.

**Comment by JodusNodus** [comment]
When you remove the parenthesis the function won't be called.

**Comment by JodusNodus** [comment]
The md-gum-polyfill. Is just a poly fill for navigator.getUsetMedia.

**Comment by gdromero** [comment]
I'm using webpack

**Comment by JodusNodus** [comment]
Seems like it is a problem of the poly fill itself. I have never had this problem using webpack.
