### ISSUE TITLE
ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by lacymorrow** [JodusNodus/react-qr-reader#91]
ReferenceError: Blob is not defined
    at createBlob (/Users/tmorrow/repo/swag-store/node_modules/react-qr-reader/lib/createBlob.js:10:5)
    at Object.<anonymous> (/Users/tmorrow/repo/swag-store/node_modules/react-qr-reader/lib/index.js:32:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.react-qr-reader (/Users/tmorrow/repo/swag-store/.next/server/static/development/pages/index.js:944:18)

**Comment by sharkyze** [comment]
I am having the same issue when server side rendering. Where you able to solve this ?

**Comment by JodusNodus** [comment]
Indeed sounds like a SSR issue. As Blobs are a feature of modern Web browsers only. The component needs to be client rendered so just exclude it from your SSR. Also could be because you are browser that doesnt support Blobs. Could you eletborate on your setup?

**Comment by lacymorrow** [comment]
Just as @JodusNodus mentioned, the issue was due to attempting to render the component via Node on the server. The fix was to test to ensure I was in a browser, not a NodeJS process.

There are a few ways to accomplish this, (potentially with `process.browser`) but I used the following above my imports:

```js
if (typeof window != 'undefined') {
    var QrReader = require('react-qr-reader')
}
import Component from 'react'
// ... All other imports, etc.
```

cc @sharkyze

**Comment by JodusNodus** [comment]
@lacymorrow Great, i'll add info about SSR into the README.

**Comment by sharkyze** [comment]
I was doing the same thing, attempting to render the component on the server. @lacymorrow suggestion worked for me. Thank you both so much

**Comment by anuragkhanra** [comment]
using dynamic import without ssr seems to work for me: 

```
import dynamic from 'next/dynamic'
const DynamicComponent = dynamic(
    () => import('../../../components/QrReaderComponent'),
    { ssr: false }
)
return (
       <DynamicComponent  />
)
```
here's the docs for ref: [https://nextjs.org/docs/advanced-features/dynamic-import](https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by afzdev13** [comment]
> @lacymorrow Great, i'll add info about SSR into the README.

Hi Jodus Nodus, as anuragkhanra mentioned in a comment it's just a matter of using the dynamic module of the next and that solves the problem, so you could add this solution to read me for those who use the Next framework
