### ISSUE TITLE
Is there a way to use a camera in the PWA?

### ISSUE THREAD

**Issue by Ivanko5417** [JodusNodus/react-qr-reader#92]
In Safari everything is working. But when I add the app to the home screen and launch it I get a white screen. (or empty space where should be `QrReader` if to use `legacymode`).
tested on iPhone 5s, 6; ios 12.0

**Comment by JodusNodus** [comment]
Please check for error being throw by `onError` and act accordingly. If the errors still occurs reopen this issue.
