### ISSUE TITLE
Uncaught (in promise) DOMException: The play method is not allowed by the user agent.

### ISSUE THREAD

**Issue by galileomd** [JodusNodus/react-qr-reader#93]
Anyone else getting this error in chrome on regular laptop/desktop?  Then the camera doesnt load.

The component seems to work fine in safari, funny enough.

**Comment by itsashis4u** [comment]
@galileomd How did it get fixed?

**Comment by galileomd** [comment]
turns out i had a conflicting browser plugin


From: Ashish Kumar Badtiya <notifications@github.com>
<notifications@github.com>
Reply: JodusNodus/react-qr-reader
<reply@reply.github.com>
<reply@reply.github.com>
Date: December 6, 2018 at 4:33:19 AM
To: JodusNodus/react-qr-reader <react-qr-reader@noreply.github.com>
<react-qr-reader@noreply.github.com>
CC: galileomd <swang@galileomd.com> <swang@galileomd.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [JodusNodus/react-qr-reader] Uncaught (in promise)
DOMException: The play method is not allowed by the user agent. (#93)

@galileomd <https://github.com/galileomd> How did it get fixed?
