### ISSUE TITLE
How to config react-qr-reader vs nextjs ?

### ISSUE THREAD

**Issue by sunkid1995** [JodusNodus/react-qr-reader#96]
@JodusNodus help me :( i not can use react-qr-reader vs nextjs

**Comment by trolund** [comment]
You can do like this:
const QrReader = dynamic(() => import('react-qr-reader'), {
  ssr: false
})


      <QrReader
        delay={300}
        onError={handleError}
        onScan={handleScan}
      />

**Comment by jailsonpaca** [comment]
Dont's forget to import :  import dynamic from "next/dynamic";

**Comment by diegoulloao** [comment]
> You can do like this: const QrReader = dynamic(() => import('react-qr-reader'), { ssr: false })
> 
> ```
>   <QrReader
>     delay={300}
>     onError={handleError}
>     onScan={handleScan}
>   />
> ```

@trolund explanation for this?
