### ISSUE TITLE
Issue while running in chrome v71 as it sets autoplay policy set to user gesture

### ISSUE THREAD

**Issue by itsashis4u** [JodusNodus/react-qr-reader#98]
`chrome://flags/#autoplay-policy`
https://developers.google.com/web/updates/2018/11/web-audio-autoplay

Also errors out for `webviews`

**Comment by JodusNodus** [comment]
Can be a problem indeed.

> However, if the user arrives on a page with autoplay content and they navigated to that page from a page of the same origin, then that content will never be blocked. Read our earlier blog post on the autoplay policy for more detailed examples.

As explained by the document the way to get around this is to make it not the first page a user visits.

**Comment by JodusNodus** [comment]
Closed the issue as this is out of the scope of this module.
